### ISSUE TITLE
Ping/tracert from CPE to internet via ACS

### ISSUE THREAD

**Issue by LeVanVuong93** [genieacs/genieacs-gui#100]
Hi everybody,

I was setup GenieaACS successfully. Currently,  i'm research to how to CPE ping / tracert to a public IP address and return result on ACS.
Who built this feature, can you tell me how to do it?
Many thanks!

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please close this
issue and take your question to the mailing list. Additionally, please do
not open the same issue on both issue trackers.
