### ISSUE TITLE
Missing documentation on how to install and run GUI.

### ISSUE THREAD

**Issue by mluis** [genieacs/genieacs-gui#108]
The documentation is not stated on the README so it is not easily found.
How do one install and run the GUI ?

**Comment by DrumSergio** [comment]
Hi @mluis 

You can find deployment scripts using Docker Compose here: https://github.com/genieacs/genieacs/wiki/Docker-Installation-with-Docker-Compose

It includes genieacs-gui, of course

Have a nice day.
