### ISSUE TITLE
Add new preset

### ISSUE THREAD

**Issue by pivasoftware** [genieacs/genieacs-gui#109]
I would like to add a new preset to trigger a Set value RPC when the CPE initiates a session with Event "1 BOOT", but this preset configuration does not work.
How can I perform such preset ?
![preset](https://user-images.githubusercontent.com/7128758/56151584-73e4d880-5fa9-11e9-9f21-000df33566fa.png)

**Comment by akcoder** [comment]
Github is for defect tracking, not support requests. Please close this
issue and take your question to the forum <https://forum.genieacs.com/>.

-dan
