### ISSUE TITLE
NBI raises MongoError when browsing through a lot of devices with sorting

### ISSUE THREAD

**Issue by okraits** [genieacs/genieacs-gui#71]
This is an issue with both genieacs v1.0 and 1.1.

When there are a lot of devices (it should happen with ~ 250, I have it here with ~ 900) and one is browsing through the devices pages with sorting by any column activated then there occurs a MongoError when accessing page 22 (with 10 devices per page):

First v1.0:

http://10.1.3.102:3000/devices?page=22&query={}&sort=summary.serialNumber

`2017-05-16T06:38:17.618Z - MongoError: too much data for sort() with no index.  add an index or specify a smaller limit
    at Object.toError (/home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/mongodb/cursor.js:714:54
    at Cursor.close (/home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
    at commandHandler (/home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/mongodb/cursor.js:714:21)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at /home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Server.Base._callHandler (/home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)

16 May 08:38:17 - Worker 942 died (0)`

This also happens with v1.1:

http://10.1.3.102:3000/devices?page=22&query={}&sort=InternetGatewayDevice.DeviceInfo.SerialNumber

`2017-05-16T06:57:09.258Z [ERROR] Uncaught exception; exceptionName="Error" exceptionMessage="Can't set headers after they are sent." exceptionStack="Error: Can't set headers after they are sent.\n    at ServerResponse.setHeader (_http_outgoing.js:371:11)\n    at ServerResp
onse.writeHead (_http_server.js:183:21)\n    at throwError (/home/okraitschy/genieacs/genieacs/lib/nbi.js:94:18)\n    at /home/okraitschy/genieacs/genieacs/lib/nbi.js:709:13\n    at handleCallback (/home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/utils.js:120:56)\n    at /home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/cursor.js:745:22\n    at handleCallback (/home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/utils.js:120:56)\n    at /home/okraitschy/genieacs/genieacs/node_modules/mongodb/lib/cursor.js:681:20\n    at handleCallback (/home/okraitschy/genieacs/genieacs/node_modules/mongodb-core/lib/cursor.js:171:5)\n    at /home/okraitschy/genieacs/genieacs/node_modules/mongodb-core/lib/cursor.js:585:22"                                                                             2017-05-16T06:57:25.236Z [ERROR] Worker died; pid=1462 exitCode=1`

**Comment by hplan** [comment]
mongodb support max 32M memory to sort, if your datas was larger than 32M will throw this exception, you can use aggregation or create a index to fix this problem.

**Comment by okraits** [comment]
Thank you for your answer. Creating an index fixes the problem. What would be the appropriate way to create a bunch of indexes when installing genieacs via npm?

**Comment by okraits** [comment]
As a reference to others, I'll attach what I use to create indexes:

```javascript
db = connect("localhost:27017/genieacs");
// create indexes for all columns on the devices page
db.devices.createIndexes([
  {"InternetGatewayDevice.DeviceInfo.SerialNumber._value": 1},
  {"InternetGatewayDevice.DeviceInfo.ProductClass._value": 1},
  {"InternetGatewayDevice.DeviceInfo.SoftwareVersion._value": 1},
  {"InternetGatewayDevice.DeviceInfo.UpTime._value": 1},
  {"_tags": 1},
  {"_lastInform": 1}
], {background : true});
db.logout();
```

**Comment by arhicks** [comment]
Would it be possible for you to share where this code needs to be added, please?  We are encountering the same issue with a ~800 device setup.

**Comment by okraits** [comment]
This is the content of a file `mongo-setup.js` which is executed with the command `mongo mongo-setup.js` by the user who executes the genieacs processes.
